 - hosts: all
   become: yes
   vars:
    postgresql_version: "13"
    postgresql_database: 
     - user: omero
       password: omero
       databases: [omero]
      
    -role: ome.omero_server
        omero_server_selfsigned_certificate: true
        omero_server_rootpassword: ChangeMe

    tasks:
    - name: Set OS distribution dependent variables
      include_vars: "{{ ansible_facts['os_family'] | lower }}.yml"
      when: ansible_facts['os_family'] == "Debian"

    roles:
    - role: ome.postgresql
    - role: ome.omero_server
    - role: ome.omero_web
 
