---
- hosts: all
  become: true

  vars:
    postgresql_version: "13"
    postgresql_databases:
      - name: omero
    postgresql_users:
      - name: omero
        password: omero
        databases: [omero]
    omero_server_selfsigned_certificates: true
    omero_server_rootpassword: ChangeMe

  pre_tasks:
    - name: Set OS distribution dependent variables
      include_vars: "{{ ansible_facts['os_family'] | lower }}.yml"
      when: ansible_facts['os_family'] == "Debian"

  roles:
    - role: ome.postgresql
    - role: ome.omero_server
    - role: ome.omero_web
